// list of constants

module.exports = {

	// Errors
	ERROR_INVALID: 'INVALID_VALUE',
	ERROR_DUPLICATE: 'DUPLICATE',
	ERROR_REDDIT_AUTH: 'REDDIT_AUTH_ERROR',
	ERROR_UNIQUE: 'EXPECTED_UNIQUE_VALUE',
	ERROR_NOT_FOUND: 'NOT_FOUND',
	ERROR_WRONG_ENTITY_ID: 'WRONG_ENTITY_ID',
	ERROR_REQUIRED: 'REQUIRED',
	ERROR_AUTH_REQUIRED: 'AUTH_REQUIRED',
	ERROR_ACCESS_DENIED: 'ACCESS_DENIED',
	ERROR_INACTIVE_USER: 'INACTIVE_USER',
	ERROR_INTERNAL: 'INTERNAL_ERROR',
	ERROR_TYPE: 'WRONG_TYPE',
	ERROR_TIME_RESTRICTION: 'TIME_RESTRICTION',
	ERROR_VOTE_TWICE: 'VOTE_TWICE',
	ERROR_ALREADY_REMOVED: 'ALREADY_REMOVED',
	ERROR_DISABLED: 'TEMPORARY_DISABLED',
	ERROR_STATUS: 'STATUS_ERROR',

	TODO_TYPES: {
		DONE: 'DONE',
		OPEN: 'OPEN',
		ABANDON: 'ABANDON',
		IN_PROGRESS: 'IN_PROGRESS'
	},

	// things
	ROLES: {
		USER: 2,
		ADMIN: 10
	}
};
